export class Imagen{
    id!:string;
    pageURL!:string;
    type!:string;
    tags!:string;
    previewURL!:string;
    previewWidth!:string;
    previewHeight!:string;
    webformatURL!:string;
    webformatWidth!:string;
    webformatHeight!:string;
    largeImageURL!:string;
    imageWidth!:string;
    imageHeight!:string;
    imageSize!:string;
    views!:string;
    downloads!:string;
    collections!:string;
    likes!:string;
    comments!:string;
    user_id!:string;
    user!:string;
    userImageURL!:string;
}
